// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiAGxNkdTHAPiBD7R2t8KQbmoB-kvOQUY',
    appId: '1:84294909906:web:ba8773e204c698a6ae120b',
    messagingSenderId: '84294909906',
    projectId: 'realshare-d1c01',
    authDomain: 'realshare-d1c01.firebaseapp.com',
    storageBucket: 'realshare-d1c01.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm0X9rsHbghYDwKmjZr8pGKdGHmrxJ8PY',
    appId: '1:84294909906:android:ff8dfa03f49d2a6eae120b',
    messagingSenderId: '84294909906',
    projectId: 'realshare-d1c01',
    storageBucket: 'realshare-d1c01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl5NGKKcxkLRAjDTwXOz5vWSP5j6T1KuA',
    appId: '1:84294909906:ios:d2d0121542940251ae120b',
    messagingSenderId: '84294909906',
    projectId: 'realshare-d1c01',
    storageBucket: 'realshare-d1c01.appspot.com',
    androidClientId: '84294909906-t7t7kl8i6f6kiko1b9eeuq2pa0qr19jg.apps.googleusercontent.com',
    iosClientId: '84294909906-0u98jcvin30c51mrfajv0qq9rgl7uuo5.apps.googleusercontent.com',
    iosBundleId: 'com.example.realstate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDl5NGKKcxkLRAjDTwXOz5vWSP5j6T1KuA',
    appId: '1:84294909906:ios:d2d0121542940251ae120b',
    messagingSenderId: '84294909906',
    projectId: 'realshare-d1c01',
    storageBucket: 'realshare-d1c01.appspot.com',
    androidClientId: '84294909906-t7t7kl8i6f6kiko1b9eeuq2pa0qr19jg.apps.googleusercontent.com',
    iosClientId: '84294909906-0u98jcvin30c51mrfajv0qq9rgl7uuo5.apps.googleusercontent.com',
    iosBundleId: 'com.example.realstate',
  );
}
